version: '3.8'

services:
  # Your website
  website:
    build: .
    ports:
      - "3000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://techparts:password123@mysql:3306/techparts_db
    depends_on:
      - mysql
    volumes:
      - ./uploads:/app/uploads  # For file uploads if needed

  # MySQL Database
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: techparts_db
      MYSQL_USER: techparts
      MYSQL_PASSWORD: password123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Initialize database
    restart: unless-stopped

  # PhpMyAdmin (Optional - for easy database management)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: techparts
      PMA_PASSWORD: password123
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_data: